### PR TITLE
Add controllers and uvm

### PR DESCRIPTION
**Pull request by M0stafaRady**
- Add AHB controller
- Add AHB wrapper 
- Fix the wishbone controller 
- Add verification environment 

CI is failing the GL simulation because it  can't synthesis the behavior models, A change to the CI to skip GL sims for such a repos would be added in the central CI repo.

### CODE REVIEW

**Comment by M0stafaRady** [comment]
> What is wrong with the wishbone controller?

There is a bug that would prevent accessing 3/4 of the memory space.

**Comment by DavidRLindley** [comment]
Are there any risks skipping GL simulations?

**Comment by M0stafaRady** [comment]
> Are there any risks skipping GL simulations?

I don't think so. 
The main reason of the CI is to synthesis the RTL then run GL sims. Since a very small portion of the code is synthesizable it should not affect much.

**Comment by DavidRLindley** [comment]
Does this bug affect the RAMs on the SRAM-TC taped out on 2404 and 2406?

**Pull request merged**
